# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gîte de La Mournette
name: Laëtitia et André Laignel
email: laetitia.laignel04@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Le Gîte la La Mournette est un gîte de France classé 2 épis situé au cœur des montagnes de Haute Provence.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gite-la-mournette.fr" # the base hostname & protocol for your site
locale: "fr"

# Build settings
exclude: [deploy.sh, README.md, LICENSE, Gemfile, Gemfile.lock, vendor]
markdown: kramdown
theme: minimal-mistakes-jekyll

facebook:
  username: "lamournette"