# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gîte de La Mournette
email: laetitia.laignel04@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ce gîte est top.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.gite-de-la-mournette.fr" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
exclude: [README.md, LICENSE, Gemfile, Gemfile.lock]
markdown: kramdown